server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:${server.port}

management.endpoints.web.exposure:
  include: '*'

management.endpoint:
  health:
    show-details: always

de.opengreenhouse.core.elastic:
  host: 192.168.178.25
  port: 9200
  schema: http